version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=true
      - API_V1_STR=/api/v1
      - BACKEND_CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://frontend:5173
      - OPENAI_MODEL=gpt-3.5-turbo
      - OPENAI_MAX_TOKENS=2000
      - OPENAI_TEMPERATURE=0.7
      - RATE_LIMIT_PER_MINUTE=60
      - LOG_LEVEL=INFO
      - SECRET_KEY=your-secret-key-change-in-production
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - agentic-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/v1/health')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      no_cache: true
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - agentic-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  agentic-network:
    driver: bridge

volumes:
  backend_data:
  frontend_data:
